version: '3.3'

services:
  app:
    build:
      context: ../.
      dockerfile: dockerfile
      args:
        APP: ${APP}
        BRANCH: ${BRANCH}
        FLAVOR: ${FLAVOR}
        WORKSPACE: ${WORKSPACE}
        BUILD_NUMBER: ${BUILD_NUMBER}
        
