version: '3.3'

services:
  app:
    image: kalisio/${APP}:${VERSION_TAG}
    environment:
      - GOOGLE_MAIL_USER
      - GOOGLE_MAIL_PASSWORD
      - APP_SECRET
      - SNS_ACCESS_KEY
      - SNS_SECRET_ACCESS_KEY
      - SNS_ANDROID_ARN
      - S3_ACCESS_KEY
      - S3_SECRET_ACCESS_KEY
      - S3_BUCKET
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - BUILD_NUMBER
      - NODE_APP_INSTANCE=${FLAVOR}
      - STRIPE_SECRET_KEY
      - STRIPE_PUBLIC_KEY
      - DB_URL
    networks:
      - app-network

networks:
  app-network:
    external:
      name: ${DOCKER_NETWORK}
