version: '3.3'

services:
  app:
    environment:
      - DEBUG=
      - DB_URL=mongodb://mongodb:27017/${APP}
    working_dir: /opt/${APP}
    depends_on:
      - mongodb    
    volumes:
      - ../server-coverage:/opt/${APP}/api/coverage
    command: [ "npm", "run", "test:server" ]
